# basic vars to make the templates cleaner
module_openapi_security__copyright: "Copyright {{ ansible_date_time.year }} Red Hat"
module_openapi_security__version_added: "1.0.0"
temp: "/tmp/{{ ansible_date_time.iso8601_basic | hash('md5') }}"

# set transport to httpapi unless overridden in cli
module_openapi_security__transport: httpapi

module_openapi_security__parent_directory: "{{ collection['path'] }}/plugins"

module_openapi_security__import_path: "ansible_collections.{{ collection['namespace'] | default('') }}.\
  {{ collection['name'] | default('') }}.plugins.modules.{{ collection['name'] }}_{{ resource }}"

# each of the files to be templated
module_openapi_security__resource_module_templates:

  - source: module_directory/resource_module.py.j2
    destination: "{{ parent_directory }}/modules/{{ plugin['name'] }}.py"
    overwrite: true

  - source: action_directory/{{ collection['namespace'] }}/resource_action_plugin.py.j2
    destination: "{{ parent_directory }}/action/{{ plugin['name'] }}.py"
    overwrite: false
