# basic vars to make the templates cleaner
module_network_netconf__copyright: "Copyright {{ ansible_date_time.year }} Red Hat"
module_network_netconf__version_added: "1.0.0"

module_network_netconf__network_os: "{{ collection['name'] }}"

module_network_netconf__import_path: "ansible_collections.{{ collection['namespace'] }}.{{ collection['name'] }}.plugins.module_utils.network"
